**Step 1 : Import Libraries**

In [1]:
import pandas as pd

**Step 2 : Load Dataset**

In [3]:
df = pd.read_csv("Dataset .csv")
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

**Step 3 : Handling Missing Values**

In [4]:
df["Cuisines"]=df["Cuisines"].fillna("Unkown")

In [5]:
df["Cuisines"]

0             French, Japanese, Desserts
1                               Japanese
2       Seafood, Asian, Filipino, Indian
3                        Japanese, Sushi
4                       Japanese, Korean
                      ...
9546                             Turkish
9547     World Cuisine, Patisserie, Cafe
9548              Italian, World Cuisine
9549                     Restaurant Cafe
9550                                Cafe
Name: Cuisines, Length: 9551, dtype: object

**Step 4 : Creating the recommendation Function**

In [21]:
def recommend_restaurants(cuisine,price_range):
    recommendations = df[
        (df["Cuisines"].str.contains(cuisine,case = False, na=False))&(df["Price range"] == price_range)]
    return recommendations[[
    "Restaurant Name",
    "Cuisines",
    "Average Cost for two",
    "Aggregate rating"
    ]]

In [22]:
recommend_restaurants("Italian",2)

,Restaurant Name,Cuisines,Average Cost for two,Aggregate rating
110,DePalma's Italian Cafe - Downtown,"American, Italian, Pizza",25,4.0
111,DePalma's Italian Cafe - East Side,"American, Italian, Pizza",25,4.1
131,Giuseppe's Pizza & Italian Specialities,"Desserts, Italian, Pizza",25,4.1
132,Mellow Mushroom,"Italian, Pizza, Sandwich",25,4.4
146,Flatbread Neapolitan Pizzeria,"Italian, Pizza",25,4.6
...,...,...,...,...
9203,Falafel Lovers,"Lebanese, Italian",650,4.3
9218,Kaphi Pibama,"Cafe, Mexican, Italian, Fast Food",500,3.8
9234,Pizza Hut,"Pizza, Italian",600,4.1
9269,Six Degrees,"South Indian, Chinese, Continental, Italian, N...",600,4.1
9414,San Carlo,Italian,25,4.3

**Step 5 : Recommend the Highest-Rating Restaurants First**

In [30]:
def recommend_restaurants(cuisine,price_range):
    recommendations=df[
        (df["Cuisines"].str.contains(cuisine,case=False,na=False))&(df["Price range"] == price_range)]
    recommendations=recommendations.sort_values(by="Aggregate rating",ascending=False)
    return recommendations[[
        "Restaurant Name",
        "Cuisines",
        "Average Cost for two",
        "Aggregate rating"
    ]]

In [31]:
recommend_restaurants("Italian",2)

,Restaurant Name,Cuisines,Average Cost for two,Aggregate rating
6997,Echoes Satyaniketan,"Cafe, Continental, Italian, Mexican, Chinese, ...",600,4.7
734,ECHOES Koramangala,"Continental, American, Italian, North Indian, ...",950,4.7
1312,Twigly,"Continental, Italian, Pizza, Asian",500,4.6
3310,Spezia Bistro,"Cafe, Continental, Chinese, Italian",900,4.6
146,Flatbread Neapolitan Pizzeria,"Italian, Pizza",25,4.6
...,...,...,...,...
8979,Bean Machine & Co.,"Italian, Continental, American",500,0.0
8935,Yeoh,"North Indian, Chinese, Italian, Thai",500,0.0
4384,Hide Out Cafe,"Cafe, Chinese, Italian",700,0.0
8269,RV's Family Restaurant,"North Indian, South Indian, Italian, Chinese",500,0.0
2211,iKitchen,"North Indian, Chinese, Italian",650,0.0

**Step 6 : Recommend Restaurants based on user preferences**

In [33]:
cuisine= input("Enter preferred cuisine:")
price_range = int(input("Enter price range (1-4): "))

recommend_restaurants(cuisine,price_range)

Enter preferred cuisine: chinese
Enter price range (1-4):  3

,Restaurant Name,Cuisines,Average Cost for two,Aggregate rating
2409,Barbeque Nation,"North Indian, Chinese",1600,4.9
2414,Barbeque Nation,"North Indian, Chinese",1600,4.9
1838,Matchbox,"Continental, North Indian, Chinese",1500,4.8
2483,The Fusion Kitchen,"North Indian, Italian, Chinese, Mexican",1000,4.7
2398,Asia Kitchen by Mainland China,"Asian, Chinese",1400,4.6
...,...,...,...,...
5092,Taste of India,"North Indian, Mughlai, Chinese",1000,0.0
5419,Moets Curry Pot,"North Indian, Chinese, Italian",1200,0.0
6060,Metro Bar & Family Restaurant,"North Indian, Chinese",1000,0.0
8479,Crazy Noodles,"Chinese, Thai",1100,0.0
902,The Retriever,"North Indian, Mughlai, Chinese",1500,0.0

**Step 7 : Conclusion:**

A restaurant recommandation system was developed using Python and Pandas.The system recommends restaurants based on the user's preferred cuisine and 
price range.The recommendations are sorted by aggregate rating so that the highest-rated restaurants are shown first.